spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:mysql://${SERVER}:3306/${DATABASE}
  config:
    activate:
      on-profile: local ,default

aws:
  s3:
    region: ${REGION}
    bucket-name: ${BUCKET}
    directory: ${DIRECTORY}
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}


---
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
    url: jdbc:mysql://${SERVER}:3306/${DATABASE}
  config:
    activate:
      on-profile: prod

aws:
  s3:
    region: ${REGION}
    bucket-name: ${BUCKET}
    directory: ${DIRECTORY}
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
