spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: impati
    url: jdbc:mysql://localhost:3306/reservation

aws:
  s3:
    region: ${REGION}
    bucket-name: ${BUCKET}
    directory: ${DIRECTORY}
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
